version: '3'

services:
  createcoursedbsvcapp:
    build: 
      context: ./createdbsvc
    image: sansubba/coursesvc-createdb-alpine:1.0
    depends_on:
      - maria_db
    networks:
      - svcnet

  courseapi:
    build:
      context: ./courseapi
    image: sansubba/courseapi-alpine:1.0
    depends_on:
      - rabbit_mq
    ports:
      - 8080:8080
    networks:
      - svcnet

  coursesvc:
    build: 
      context: ./coursesvc
    image: sansubba/coursesvc-alpine:1.0
    depends_on:
      - rabbit_mq
      - createcoursedbsvcapp
      - maria_db
    networks:
      - svcnet

  maria_db:
    image: mariadb:latest
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - MARIADB_DATABASE=courses
    networks:
      - svcnet
    ports:
      - 3306:3306

  rabbit_mq:
    image: rabbitmq:3-management
    networks:
      - svcnet
    ports:
      - 15672:15672
      - 5672:5672

networks:
  svcnet:
    driver: bridge