version: '3'

services:
  createcoursedbsvcapp:
    build: ./createdbsvc
    image: sansubba/coursesvc-createdb-alpine:1.0
    depends_on:
      - maria_db
    networks:
      - svcnet

  courseapi:
    build: ./courseapi
    image: sansubba/coursesvc-createdb-alpine:1.0
    depends_on:
      - maria_db
    networks:
      - svcnet

  coursesvc:
    build: ./coursesvc
    image: sansubba/coursesvc-createdb-alpine:1.0
    depends_on:
      - maria_db
      - rabbit_mq
    networks:
      - svcnet

  maria_db:
    image: mariadb:latest
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - MARIADB_DATABASE=courses
    networks:
      - svcnet

  rabbit_mq:
    image: rabbitmq:3-management
    networks:
      - svcnet

networks:
  svcnet:
    driver: bridge